### PR TITLE
Mac build

### LINKED ISSUE #42: readme describes installation on a specific computer
The readme should describe how to install the code on _any_ *nix based computer or at least a specific generic one, like ubuntu or macos. A link can be included to Phoenix or other specific install instructions in version control.

### PR DESCRIPTION
**Pull request by suzm10**
- [X] MacOS Runner
- [X] Upgrade to latest PETSc version
- [X] Mini case with 2 cells and less wall points
- [X] Fixed miscellaneous compiler errors and warnings in codebase (there are more i didn't fix but they probably should be in the future)
- [X] Readme only describes mac build (ubuntu in the future if I get access to an ubuntu computer?)
  - @sbryngelson I think I need help explaining things better in the readme and accounting for install failure cases, but I tried my best.
- [X] Need to wait for next NetCDF-Fortran release to install it properly on mac, but I found a hack around it. I don't fully trust it though.

Known bugs that I have no fixes for:
- The `call PetscFinalize(ierr)` line in the `FinalizeMPI` subroutine will cause the program (`initcond.F90`) to freeze if you're connected to the gatech VPN
  - also can't successfully configure petsc while connected to vpn
- can't configure petsc if conda activated in your shell
- mpiexec generates random copies of `initcond` that you have to delete yourself or else cmake fails

### CODE REVIEW

**Comment by suzm10** [comment]
I would clean this up and open a PR, but I tried my `./rbc.sh install-mac` on another mac, and I'm getting a link error on petsc `make all`. I had to use the same flag inside my `CMakeLists.txt`, so this issue has to be resolved. @sbryngelson have you tried it in you environment?

```
CLINKER arch-darwin-c-opt/lib/libpetsc.3.21.3.dylib
ld: unknown option: -no_warn_duplicate_libraries
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sbryngelson** [comment]
This worked on my machine. The reason it didn't work here is that it is using clang, not gcc. if you `export CC=gcc-13` `export CXX=g++-13` `export FC=gfortran-13` (or replace 13 with 12 or 14, whatever your version is), it should work.

**Comment by suzm10** [comment]
hm that's weird because i'm pretty sure it has to be using mpicc, mpicxx, and mpif90 with the `./configure` options

**Comment by sbryngelson** [comment]
mpicc/cxx can point to an underlying clang compiler, they are just interfaces between the underlying compiler and mpi api.

**Comment by suzm10** [comment]
o makes sense. it also seems to work a lot better with brew installed mpich than openmpi for me

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
