### PR TITLE
Phoenix Runner

### LINKED ISSUE #6: Dependencies are outdated
This codebase carries several _very_ out of date dependencies. This makes it quite challenging to build and likely affects performance. Resolving this issue would substitute more up-to-date or modern/difference packages for such things. Below are some example packages.

- [X] Intel MKL (current version very very old)
- [X] GMRES solver (currently a hardcoded file?)
- [X] Build system relying upon `makedepf90`
- [X] PETSc (current version very very old)

### PR DESCRIPTION
**Pull request by suzm10**
All the updates in this PR:
- [X] Top-level CMakeLists.txt
  - /common CMakeLists.txt because I added common as a subdirectory (easy re-factor, but I thought it made sense for a library)
  - cases are custom targets with their own binary directory inside `/build`
  - warnings if it can't find packages
  - support both module loaded PETSc and package installed PETSc (I don't think the PETSC_INCLUDE_DIRS naturally handles both, so this is messy sorry)
- [X] Case file renames
- [x] Kept old Makefiles to leave that option
- [X] Readme updates
  - This is confusing since the install script that works on my account doesn't work on all Phoenix accounts.
- [X] Working Phoenix runner
  - Had to custom install Lapack and FFTW in `/packages` for `ml gcc/12.1.0-qgxpzk mvapich2/2.3.7-733lcv` to work since the FFTW module depends on `mvapich2/2.3.6-ouywal`, and that one is broken inside the Phoenix runner. This install script is now under `install-phoenix.sh`, but it’s more of a worst-case scenario because `install.sh` works for me on Phoenix. `install.sh` does work on the ICE runner because the ICE FFTW depends on the default `mvapich2/2.3.7-1` already.
  - Tests both with Makefiles and CMake. `Makefile.in` isn't flexible at all though (there's nothing I can do about this), so it doesn't work with all builds.

### CODE REVIEW

**Comment by sbryngelson** [comment]
please rebase so there aren't so many commits

**Comment by suzm10** [comment]
i took out the the line that lets you see a PR's commits on master but okay i'll try. the commit history on this is really complicated from having to add and remove my own cases.

**Comment by sbryngelson** [comment]
this has commits from 3 weeks ago?

**Comment by suzm10** [comment]
yeah i basically kept the same branch that i made other PRs from but ran a "git merge master" after pulling the PR onto master and never started a new branch, so the real differences start after #[8ec18f5](https://github.com/comp-physics/RBC3D/pull/41/commits/8ec18f534315d124f90d215765b5a09ceba6bf4d). sorry this is so hacky, i'm trying to resolve conflicts in the rebase now, but there's conflicts in all 96 commits, so it's too cumbersome.

**Comment by suzm10** [comment]
I just reset the commit history. Some of the Makefiles on the branch might look old, but that was because I gave all the case files unique names, so a global Makefile wasn't gonna work anymore without some wildcards. I'm hoping Makefiles can be completely removed in the future though if I'm happy with cmake. It handles everything pretty dynamically, but if you need a better explanation of the system I set up, I can try!

**Comment by suzm10** [comment]
Maybe someone else could help with the review if they're familiar with cmake? It's pretty much identical to Makefile.in and [PETSc's official cmake](https://github.com/petsc/petsc/blob/73667fc30d32dc826fe556678ead0a5035a1b26b/share/petsc/CMakeLists.txt#L9).

**Comment by suzm10** [comment]
@sbryngelson look Phoenix runner works! I'm not putting a MacOS runner in the same PR though cause there's already too much here. The CMake works on Mac too though.

**Comment by suzanmanasreh** [comment]
Wait should ICE runner be taken out now? I don't know

**Review by sbryngelson — APPROVED** [review]

**Pull request merged**
