### PR TITLE
Electrodrops

### PR DESCRIPTION
**Pull request by suzm10**

### CODE REVIEW

**Comment by sbryngelson** [comment]
but how do I use it?

**Comment by suzm10** [comment]
Firouznia's example case is the same as our case, so I just removed that. Not sure how he used it.

**Comment by suzm10** [comment]
Creating an example case for it might be another ticket. If you want an example for it in this PR, I can close this and come back to it later.

**Comment by sbryngelson** [comment]
Yes, right now it's not clear how to use the functions added by this module.

**Pull request closed without merging**
